CREATE TABLE `user` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `openid` VARCHAR(64) NOT NULL UNIQUE,
  `nickname` VARCHAR(100),
  `avatarUrl` TEXT,
  `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE `upload_record` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `imageUrl` TEXT NOT NULL,
  `type` VARCHAR(50) DEFAULT 'unknown', -- handwrite / invoice / general / ...
  `uploadTime` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `lastModified` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `resultText` TEXT,
  FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE CASCADE
);
